# Generated by Django 3.1.7 on 2021-03-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210321_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image_ppoi',
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
