# Generated by Django 3.1.7 on 2021-03-15 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0003_category_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_categories', to=settings.AUTH_USER_MODEL),
        ),
    ]
