# Generated by Django 3.1.7 on 2021-03-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210317_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'in_progress'), ('COMPLETED', 'completed')], default='IN_PROGRESS', max_length=12),
        ),
    ]
