# Generated by Django 3.1.7 on 2021-03-24 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_by',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_by',
        ),
    ]
