# Generated by Django 3.1.7 on 2021-03-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210317_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.PositiveIntegerField(max_length=30, unique=True),
        ),
    ]
