# Generated by Django 3.1.7 on 2021-03-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210318_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
